# Generated by Django 3.2.7 on 2021-09-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20210913_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='electricalparameters',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='electricalparameters',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
