# Generated by Django 3.2.7 on 2021-09-14 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210913_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricalparameters',
            options={'ordering': ('controller', 'created')},
        ),
        migrations.AlterField(
            model_name='electricalparameters',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='controller.controller'),
        ),
    ]
