# Generated by Django 3.2.7 on 2021-09-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20210914_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricalparameters',
            options={'ordering': ('controller', '-created')},
        ),
    ]
